name: statlock-ci
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install jsonschema pandas
      - name: Validate CFB rosters (if present)
        run: |
          if [ -f scripts/validate_cfb_rosters.py ] && [ -f data/cfb_rosters_ourlads_fbs.jsonl ]; then
            python scripts/validate_cfb_rosters.py data/cfb_rosters_ourlads_fbs.jsonl || true
          fi
          if [ -f scripts/validate_cfb_rosters.py ] && [ -f data/cfb_rosters_ourlads_fbs.csv ]; then
            python scripts/validate_cfb_rosters.py data/cfb_rosters_ourlads_fbs.csv || true
          fi
